### Create a dream
POST http://localhost:8008/dream
Content-Type: application/json

{
  "content": "Bir rüya gördüm. Rüyamda iki ekmek vardı. Biri küflüydü."
}


### Get a dream
GET http://localhost:8008/dream/14
Content-Type: application/json


### Get all dreams
GET http://localhost:8008/dreams
Content-Type: application/json