// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/yazilimcigenclik/dream-ai-backend/app/controllers"
	"github.com/yazilimcigenclik/dream-ai-backend/app/repository"
	"github.com/yazilimcigenclik/dream-ai-backend/app/services"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	dreamRepositoryImpl := repository.DreamRepositoryInit(gormDB)
	dreamServiceImpl := services.DreamServiceInit(dreamRepositoryImpl)
	dreamControllerImpl := controllers.DreamControllerInit(dreamServiceImpl)
	initialization := NewInitialization(dreamRepositoryImpl, dreamServiceImpl, dreamControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var dreamServiceSet = wire.NewSet(services.DreamServiceInit, wire.Bind(new(services.DreamService), new(*services.DreamServiceImpl)))

var dreamRepoSet = wire.NewSet(repository.DreamRepositoryInit, wire.Bind(new(repository.DreamRepository), new(*repository.DreamRepositoryImpl)))

var dreamCtrlSet = wire.NewSet(controllers.DreamControllerInit, wire.Bind(new(controllers.DreamController), new(*controllers.DreamControllerImpl)))
